const students=[{
    "id": 1,
    "first_name": "Wernher",
    "last_name": "Boater",
    "email": "wboater0@arizona.edu"
  }, {
    "id": 2,
    "first_name": "Mayer",
    "last_name": "Dilliston",
    "email": "mdilliston1@baidu.com"
  }, {
    "id": 3,
    "first_name": "Nadean",
    "last_name": "Bigmore",
    "email": "nbigmore2@shutterfly.com"
  }, {
    "id": 4,
    "first_name": "Darby",
    "last_name": "Bartalin",
    "email": "dbartalin3@timesonline.co.uk"
  }, {
    "id": 5,
    "first_name": "Nobie",
    "last_name": "Cuseick",
    "email": "ncuseick4@toplist.cz"
  }, {
    "id": 6,
    "first_name": "Abigael",
    "last_name": "Tregidga",
    "email": "atregidga5@ca.gov"
  }, {
    "id": 7,
    "first_name": "Maudie",
    "last_name": "Baseggio",
    "email": "mbaseggio6@cafepress.com"
  }, {
    "id": 8,
    "first_name": "Rockwell",
    "last_name": "Balshen",
    "email": "rbalshen7@vk.com"
  }, {
    "id": 9,
    "first_name": "Therine",
    "last_name": "Thecham",
    "email": "tthecham8@technorati.com"
  }, {
    "id": 10,
    "first_name": "Wilhelmine",
    "last_name": "Kitchener",
    "email": "wkitchener9@wordpress.com"
  }]
module.exports=students;  